services:
  - type: web
    name: imessage-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MY_IMESSAGE_NUMBER
        sync: false
      - key: IMESSAGE_API_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
